"""Generates tooling/standards/FILE_MAP.md: one line per Python module, its role.

A module's role is the first sentence of its own docstring, so the map is
only as good as those sentences and is never edited by hand. A non-empty
module without a docstring stops the generation: it would be a file nobody
can place. `tooling/verify/checks/file_map.py` regenerates the map in memory
and fails when the committed file differs.

Usage: python tooling/glue/gen_file_map.py
"""
from __future__ import annotations

import ast
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
FILE_MAP = ROOT / "tooling" / "standards" / "FILE_MAP.md"
SCOPES = ("src/world_engine", "scripts", "tooling/glue", "tooling/verify")
SKIPPED_PARTS = {"__pycache__", "node_modules", ".venv"}
SENTENCE_END = re.compile(r"[.!?](?=\s)")

HEADER = """# File map

<!-- Generated by `python tooling/glue/gen_file_map.py` from the first
     sentence of each module's docstring. Never edit by hand: change the
     docstring and regenerate. `tooling/verify/checks/file_map.py` fails
     when this file is stale. -->
"""


def modules(scope: str) -> list[pathlib.Path]:
    base = ROOT / scope
    return sorted(
        p for p in base.rglob("*.py")
        if not SKIPPED_PARTS.intersection(p.relative_to(ROOT).parts)
    )


def role(path: pathlib.Path) -> str | None:
    """The first sentence of the docstring's first paragraph; "" for an
    empty file; None for a non-empty module without a docstring."""
    source = path.read_text(encoding="utf-8")
    if not source.strip():
        return ""
    doc = ast.get_docstring(ast.parse(source))
    if not doc or not doc.strip():
        return None
    paragraph = " ".join(doc.strip().split("\n\n")[0].split())
    match = SENTENCE_END.search(paragraph)
    return paragraph[: match.start() + 1] if match else paragraph


def collect() -> tuple[dict[str, list[tuple[str, str]]], list[str]]:
    """Per directory (repo-relative, POSIX), its modules and roles; plus the
    modules that have no docstring."""
    groups: dict[str, list[tuple[str, str]]] = {}
    missing: list[str] = []
    for scope in SCOPES:
        for path in modules(scope):
            rel = path.relative_to(ROOT)
            line = role(path)
            if line is None:
                missing.append(rel.as_posix())
                continue
            if line == "":
                continue
            groups.setdefault(rel.parent.as_posix(), []).append((rel.name, line))
    return groups, missing


def render(groups: dict[str, list[tuple[str, str]]]) -> str:
    out = [HEADER]
    for directory in sorted(groups):
        out.append(f"\n## {directory}/\n\n")
        for name, line in groups[directory]:
            out.append(f"- `{name}` — {line}\n")
    return "".join(out)


def main() -> int:
    groups, missing = collect()
    if missing:
        for rel in missing:
            print(f"no module docstring: {rel}", file=sys.stderr)
        return 1
    FILE_MAP.write_text(render(groups), encoding="utf-8", newline="\n")
    print(f"wrote {sum(len(v) for v in groups.values())} modules to {FILE_MAP.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
